"""quimb-backed EDM-MPS compression (Layer 5, ecosystem path).

Replaces the hand-rolled canonicalise + truncation sweep with quimb's
``tensor_network_1d_compress`` (cotengra path-finding, autoray dispatch), so the
heavy linear algebra is the maintained quimb+cotengra+autoray stack and the whole
path is backend-agnostic (NumPy / CuPy / ... via autoray) for free.

The EDM is carried as a generic 1D :class:`quimb.tensor.TensorNetwork`: each site
tensor ``G[phi, chi_l, chi_r]`` becomes a ``Tensor`` with a physical index ``k{p}``
and virtual bonds; the operator-valued boundaries -- the dangling ``d**2`` output
leg (``OUT``) and the ``rho0`` contraction leg (``RHO0``) -- are ordinary dangling
indices that ride along the compression untouched.

This path uses a **quimb-native cutoff mode** (default ``rsum2`` -- the standard
discarded-weight criterion); the paper's ``rel_ref`` rule is intentionally retired
(validated to reproduce the observable ``<S_z(t)>`` at a smaller bond, see
``examples/quimb_fold_e2e.py``).  Arrays are kept on their native backend (no host
round-trip), so this works on the GPU.
"""

from __future__ import annotations

from .mps_utils import EDMMPS


def _edmmps_to_quimb(mps):
    """Wrap an EDMMPS as a generic quimb 1D TensorNetwork (arrays kept native)."""
    import quimb.tensor as qtn  # noqa: PLC0415

    n = mps.num_sites
    ts = []
    for p in range(n):
        left = "OUT" if p == 0 else f"v{p - 1}"
        right = "RHO0" if p == n - 1 else f"v{p}"
        ts.append(qtn.Tensor(mps.tensors[p], inds=(f"k{p}", left, right), tags={f"I{p}"}))
    return qtn.TensorNetwork(ts)


def _quimb_to_edmmps(tn, n, ref):
    """Extract per-site arrays (phi, chi_l, chi_r) from a compressed quimb TN.

    Internal bond names are regenerated by quimb's compress, so locate them by
    connectivity; arrays are kept on their native backend (``t.data``)."""
    import quimb.tensor as qtn  # noqa: PLC0415

    tensors = []
    for p in range(n):
        t = tn[f"I{p}"]
        left = "OUT" if p == 0 else list(qtn.bonds(tn[f"I{p - 1}"], t))[0]
        right = "RHO0" if p == n - 1 else list(qtn.bonds(t, tn[f"I{p + 1}"]))[0]
        tensors.append(t.transpose(f"k{p}", left, right).data)
    return EDMMPS(tensors=tensors, d=ref.d, d_phys=ref.d_phys,
                  rho0_vec=ref.rho0_vec, meta=dict(ref.meta))


def compress_quimb(mps, *, max_bond=None, cutoff=1e-12, cutoff_mode="rsum2",
                   method="zipup"):
    """Compress the EDM-MPS via quimb; returns ``(mps, info_per_bond)``.

    Parameters mirror the native ``compress`` where they overlap.  ``cutoff`` and
    ``cutoff_mode`` are quimb-native (default ``rsum2``); ``method`` selects quimb's
    1D-compress algorithm (``zipup`` is fast and accurate here).
    """
    n = mps.num_sites
    if n <= 1:
        return mps, []
    import quimb.tensor as qtn  # noqa: PLC0415

    from ..backend.quimb_linalg import apply_quimb_cupy_compat  # noqa: PLC0415

    apply_quimb_cupy_compat()  # make quimb/autoray safe on CuPy-backed tensors
    tn = _edmmps_to_quimb(mps)
    site_tags = [f"I{p}" for p in range(n)]
    cq = qtn.tensor_network_1d_compress(
        tn, max_bond=max_bond, cutoff=cutoff, cutoff_mode=cutoff_mode,
        method=method, site_tags=site_tags, permute_arrays=False)
    out = _quimb_to_edmmps(cq, n, mps)
    # per-bond truncation error is not exposed by the 1D-compress wrapper; report
    # the kept bond dims (error tracking for this path is a follow-up).
    infos = [{"bond": int(b), "error": 0.0} for b in out.bond_dims]
    return out, infos
