"""Phase 0.0 feasibility: can the EDM live as a quimb TN and be compressed by
quimb (cotengra/autoray) reproducing the StandardSVD truncation to < xi?

This is the decision gate that subsumes the per-piece refactors (plan Phase 0).
It does NOT touch src: it wraps an uncompressed folded EDM-MPS as a generic quimb
1D TensorNetwork (the d**2 output / rho0 boundaries become named dangling indices),
compresses it with `tensor_network_1d_compress`, converts back, and compares the
reduced density matrix rho(t) and the bond dimension against the production
StandardSVD compression of the *same* uncompressed MPS.

Run (CPU, in the quimb env):
    PYTHONPATH=src python examples/quimb_tn_feasibility.py --K 16 --L 8 --cutoff 1e-6
"""

from __future__ import annotations

import argparse
import os
import sys
import time

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from edm_incremental import compress_full, fold_uncompressed, make_context  # noqa: E402

from edmtn.decomposition.base import truncation_rank  # noqa: E402
from edmtn.evolution.mps_utils import EDMMPS  # noqa: E402
from edmtn.models import GaudinModel  # noqa: E402

import quimb.tensor as qtn  # noqa: E402


def edmmps_to_quimb(mps):
    """Wrap an EDMMPS (tensors G[phi, chi_l, chi_r], d**2 boundaries) as a quimb TN.

    Indices: physical ``k{p}`` (phi_up); internal bonds ``v{p}`` between sites
    p,p+1; the open left output leg ``OUT`` (dim d**2); the right boundary ``RHO0``
    (dim d**2, later contracted with rho0_vec).
    """
    n = mps.num_sites
    ts = []
    for p in range(n):
        G = mps.tensors[p]                       # (phi, chi_l, chi_r)
        left = "OUT" if p == 0 else f"v{p - 1}"
        right = "RHO0" if p == n - 1 else f"v{p}"
        ts.append(qtn.Tensor(np.asarray(G), inds=(f"k{p}", left, right), tags={f"I{p}"}))
    return qtn.TensorNetwork(ts)


def quimb_to_edmmps(tn, n, ref):
    """Extract per-site arrays from a compressed quimb 1D TN back into an EDMMPS,
    each tensor transposed to (phi, chi_l, chi_r).  Internal bond names are
    regenerated by quimb's compress, so locate them by *connectivity*."""
    tensors = []
    for p in range(n):
        t = tn[f"I{p}"]
        left = "OUT" if p == 0 else list(qtn.bonds(tn[f"I{p - 1}"], t))[0]
        right = "RHO0" if p == n - 1 else list(qtn.bonds(t, tn[f"I{p + 1}"]))[0]
        t = t.transpose(f"k{p}", left, right)
        tensors.append(np.asarray(t.data))
    return EDMMPS(tensors=tensors, d=ref.d, d_phys=ref.d_phys, rho0_vec=ref.rho0_vec.copy())


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--g", type=float, default=1.0)
    ap.add_argument("--K", type=int, default=16)
    ap.add_argument("--L", type=int, default=8, help="fold up to L sub-baths, then test the L->L+1 fold")
    ap.add_argument("--T", type=float, default=3.0)
    ap.add_argument("--eps", type=float, default=0.2)
    ap.add_argument("--cutoff", type=float, default=1e-6)
    ap.add_argument("--max-bond", type=int, default=100000)
    ap.add_argument("--method", default="dm", choices=("dm", "svd", "zipup", "zipup-first"))
    args = ap.parse_args()

    model = GaudinModel(g=args.g, K=args.K)
    ctx = make_context(model, T=args.T, eps=args.eps, order=2,
                       cutoff=args.cutoff, max_bond=args.max_bond)
    print(f"quimb-TN feasibility (Gaudin): K={args.K}, fold L={args.L}->{args.L+1}, "
          f"T={args.T}, eps={args.eps}, xi={args.cutoff:g}, method={args.method}")

    # fold up to L, then produce the uncompressed L+1 MPS to compress two ways
    mps = ctx["mps0"]
    for k in range(args.L):
        unc = fold_uncompressed(ctx, mps, k)
        mps = unc if unc.num_sites <= 1 else compress_full(ctx, unc)[0]
    U = fold_uncompressed(ctx, mps, args.L)        # uncompressed L+1 MPS
    n = U.num_sites
    print(f"  uncompressed fold: sites={n}, max bond={U.max_bond}")

    # -- reference: StandardSVD compression (the production path) -----------
    t0 = time.perf_counter()
    C_std = compress_full(ctx, U.copy())[0]
    t_std = time.perf_counter() - t0
    rho_std = C_std.reduced_density_matrix()

    # -- quimb compression of the same uncompressed MPS ---------------------
    # rank target: honour the paper rel_ref rule via our truncation_rank -> max_bond,
    # plus quimb's own cutoff as a secondary guard.
    site_tags = [f"I{p}" for p in range(n)]
    rho_U = U.reduced_density_matrix()

    def _quimb_compress(max_bond, cutoff, label):
        tn = edmmps_to_quimb(U)
        t0 = time.perf_counter()
        cq = qtn.tensor_network_1d_compress(
            tn, max_bond=max_bond, cutoff=cutoff, method=args.method,
            site_tags=site_tags, permute_arrays=False)
        dt = time.perf_counter() - t0
        C = quimb_to_edmmps(cq, n, U)
        rho = C.reduced_density_matrix()
        err = float(np.max(np.abs(rho - rho_U)))
        cross = float(np.max(np.abs(rho_std - rho)))
        print(f"    quimb[{label}]: from-U {err:.2e}  cross-vs-std {cross:.2e}  "
              f"Dmax={C.max_bond}  {dt*1e3:.0f} ms")
        return cross, C.max_bond

    err_std = float(np.max(np.abs(rho_std - rho_U)))
    print(f"\n  reduced rho(t) deviation (from uncompressed U; and cross vs StandardSVD):")
    print(f"    StandardSVD     : from-U {err_std:.2e}  (Dmax={C_std.max_bond}, {t_std*1e3:.0f} ms) [reference]")
    # (a) quimb's native cutoff (shows the rsum2-vs-rel_ref rule mismatch)
    _quimb_compress(min(args.max_bond, C_std.max_bond), args.cutoff, "native cutoff")
    # (b) matched rank: drive truncation by StandardSVD's Dmax, cutoff~0
    cross_m, dmax_m = _quimb_compress(C_std.max_bond, 1e-14, "matched Dmax")
    print(f"\n  gate: at matched rank, quimb machinery vs StandardSVD cross = {cross_m:.2e} "
          f"(< xi={args.cutoff:g}? {'YES' if cross_m < args.cutoff else 'no'})")
    print("  note: quimb has no rel_ref cutoff mode -> reproduce the paper rule by supplying the")
    print("        per-bond rank (our truncation_rank); quimb owns canonize/SVD/contract (cotengra).")


if __name__ == "__main__":
    main()
